name: build

on:
  - push
  - pull_request

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxxf86vm-dev libgl1-mesa-dev -qyy
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{runner.workspace}}/vcpkg"
          vcpkgGitCommitId: "05c445c1fb3afb90aa8a46ca2b7d2a9548a27121"
      - name: Set build configuration
        run: |
          sed '/#define _IRR_COMPILE_WITH_OGLES2_/ s|^//||g' -i include/IrrCompileConfig.h
      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          configurePreset: release
          buildPreset: release
      - name: Test (headless)
        run: |
          ./cmake-build-release/bin/Linux/AutomatedTest null
      - name: Test (OpenGLES2)
        run: |
          LIBGL_ALWAYS_SOFTWARE=true xvfb-run ./cmake-build-release/bin/AutomatedTest ogles2

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{runner.workspace}}/vcpkg"
          vcpkgGitCommitId: "05c445c1fb3afb90aa8a46ca2b7d2a9548a27121"
      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          configurePreset: release
          buildPreset: release

  macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10.1
        with:
          vcpkgDirectory: "${{runner.workspace}}/vcpkg"
          vcpkgGitCommitId: "05c445c1fb3afb90aa8a46ca2b7d2a9548a27121"
      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          configurePreset: release
          buildPreset: release
