name: build

on:
  - push
  - pull_request

jobs:

  linux-gl:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxxf86vm-dev libgl1-mesa-dev -qyy
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10.1
      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          buildPreset: default

  linux-gles:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxxf86vm-dev libgles2-mesa-dev xvfb -qyy
      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10.1
      - name: Set build configuration
        run: |
          sed '/#define _IRR_COMPILE_WITH_OGLES2_/ s|^//||g' -i include/IrrCompileConfig.h
          sed '/#define _IRR_COMPILE_WITH_OPENGL_/ s|^|//|g' -i include/IrrCompileConfig.h
      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          buildPreset: default
      - name: Test (headless)
        run: |
          cd bin/Linux
          ./AutomatedTest null
      - name: Test (Xvfb)
        run: |
          cd bin/Linux
          LIBGL_ALWAYS_SOFTWARE=true xvfb-run ./AutomatedTest

  win32:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++-mingw-w64-i686 -qyy

      - name: Build
        run: |
          ./scripts/ci-build-mingw.sh
        env:
          CC: i686-w64-mingw32-gcc
          CXX: i686-w64-mingw32-g++

  win64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++-mingw-w64-x86-64 -qyy

      - name: Build
        run: |
          ./scripts/ci-build-mingw.sh
        env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          brew update
          brew install cmake

      - name: Build
        run: |
          cmake . -DCMAKE_FIND_FRAMEWORK=LAST
          make -j3
