name: build

on:
  - push
  - pull_request

jobs:

  linux-gl:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake libxxf86vm-dev libgl1-mesa-dev -qyy

      - name: Build
        run: |
          cmake .
          make VERBOSE=1 -j2

  linux-gles:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake libxxf86vm-dev libgles2-mesa-dev xvfb -qyy

      - name: Build
        run: |
          sed '/#define _IRR_COMPILE_WITH_OGLES2_/ s|^//||g' -i include/IrrCompileConfig.h
          sed '/#define _IRR_COMPILE_WITH_OPENGL_/ s|^|//|g' -i include/IrrCompileConfig.h
          cmake . -DBUILD_EXAMPLES=1
          make -j2

      - name: Test (headless)
        run: |
          cd bin/Linux
          ./AutomatedTest null

      - name: Test (Xvfb)
        run: |
          cd bin/Linux
          LIBGL_ALWAYS_SOFTWARE=true xvfb-run ./AutomatedTest

  win32:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++-mingw-w64-i686 -qyy

      - name: Build
        run: |
          ./scripts/ci-build-mingw.sh
        env:
          CC: i686-w64-mingw32-gcc
          CXX: i686-w64-mingw32-g++

  win64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++-mingw-w64-x86-64 -qyy

      - name: Build
        run: |
          ./scripts/ci-build-mingw.sh
        env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          brew update
          brew install cmake

      - name: Build
        run: |
          cmake . -DCMAKE_FIND_FRAMEWORK=LAST
          make -j3
